make build work with both old iptables-dev and new libnetfilter-queue-dev. regenerate build files with new aclocal/autoconf/automake.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -25916,6 +25916,12 @@ fi
 
            if test "$with_libipq_includes" != "no"; then
                 CPPFLAGS="${CPPFLAGS} -I${with_libipq_includes}"
+           else
+             if test -d /usr/include/libnetfilter_queue; then
+               CPPFLAGS="${CPPFLAGS} -I/usr/include/libnetfilter_queue"
+             else
+               CPPFLAGS="${CPPFLAGS} -I/usr/include/libipq"
+             fi
            fi
 
            if test "${ac_cv_header_libipq_h+set}" = set; then
@@ -26052,11 +26058,87 @@ echo "$as_me: error: libipq.h not found ..." >&2;}
 fi
 
 
+
            if test "$with_libipq_libraries" != "no"; then
                 LDFLAGS="${LDFLAGS}  -L${with_libipq_libraries}"
            fi
 
            LIPQ=""
+
+{ echo "$as_me:$LINENO: checking for ipq_set_mode in -lnetfilter_queue_libipq" >&5
+echo $ECHO_N "checking for ipq_set_mode in -lnetfilter_queue_libipq... $ECHO_C" >&6; }
+if test "${ac_cv_lib_netfilter_queue_libipq_ipq_set_mode+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lnetfilter_queue_libipq  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char ipq_set_mode ();
+int
+main ()
+{
+return ipq_set_mode ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_netfilter_queue_libipq_ipq_set_mode=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_netfilter_queue_libipq_ipq_set_mode=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_netfilter_queue_libipq_ipq_set_mode" >&5
+echo "${ECHO_T}$ac_cv_lib_netfilter_queue_libipq_ipq_set_mode" >&6; }
+if test $ac_cv_lib_netfilter_queue_libipq_ipq_set_mode = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBNETFILTER_QUEUE_LIBIPQ 1
+_ACEOF
+
+  LIBS="-lnetfilter_queue_libipq $LIBS"
+
+else
+  LIPQ="no"
+fi
+
+           if test "$LIPQ" = "no"; then
+             LIPQ=""
 
 { echo "$as_me:$LINENO: checking for ipq_set_mode in -lipq" >&5
 echo $ECHO_N "checking for ipq_set_mode in -lipq... $ECHO_C" >&6; }
@@ -26130,6 +26212,7 @@ else
   LIPQ="no"
 fi
 
+           fi
 
            if test "$LIPQ" = "no"; then
                echo
